# Generated by Django 4.1.3 on 2022-11-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0003_pro_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_tb',
            name='category',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pro_tb',
            name='image',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
