# Generated by Django 4.1.3 on 2022-11-22 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0004_pro_tb_category_alter_pro_tb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_tb',
            name='quantity',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalamount', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.pro_tb')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.log_tb')),
            ],
        ),
    ]
