# Generated by Django 4.1.3 on 2022-11-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0005_pro_tb_quantity_cart_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro_tb',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart_tb',
            name='quantity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
