# Generated by Django 4.1.3 on 2022-11-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0008_payment_tb_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_tb',
            name='time',
            field=models.TimeField(),
        ),
    ]
