# Generated by Django 4.1.3 on 2022-11-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0010_order_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_tb',
        ),
        migrations.AddField(
            model_name='payment_tb',
            name='image',
            field=models.ImageField(default=0, upload_to='product/'),
            preserve_default=False,
        ),
    ]
