# Generated by Django 4.1.3 on 2022-11-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0011_delete_order_tb_payment_tb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_tb',
            name='hashpass',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
